spring.application.name=bibliotecaduoc
# Desactiva el reinicio automático del servidor
spring.devtools.restart.enabled=false

# Mantiene activo el servidor de LiveReload para el navegador
spring.devtools.livereload.enabled=true
